#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# path
export GOPATH=${HOME}
export PATH=${PATH}:${GOPATH}/bin
export PATH="${HOME}/.yarn/bin:${HOME}/.config/yarn/global/node_modules/.bin:${PATH}"
export PATH="${PATH}:${HOME}/Library/Python/3.7/bin"
source ${HOME}/.cargo/env

export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.homebrew_github_api_token)
export EDITOR=vi
export VISUAL=vi

