#/usr/local/opt/fzf/shell/key-bindings.zsh
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# alias
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias g='git'
alias ga='git add'
alias gd='git diff'
alias gs='git status'
alias gp='git push'
alias gb='git branch'
alias gst='git status'
alias gco='git checkout'
alias gf='git fetch'
alias gc='git commit'
alias gr='cd $(ghq root)/$(ghq list | peco)'

alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

alias b='hub browse $(ghq list | peco | cut -d "/" -f 2,3)'
alias c='pbcopy'
alias f='find . -name'
alias l='(){ exa -l -a -g --git -t modified --time-style long-iso --git --color always $1 | less -R }'
alias o='open'
alias vc='code $(ghq root)/$(ghq list | peco)'

alias ccat='ccat --color=always'
alias less='less -R'
alias pwdc='pwd | sed "s/^\(.*\)$/'\''\1'\''/" | tr -d '\''\n'\'' | pbcopy'
alias cat='bat'
alias python='python3'

alias take='(){ mkdir -p "$@" && eval cd "\"\$$#\""; }'


# history
# for peco
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE

function search_history() {
    local tac
    if which tac > /dev/null; then
        tac="tac"
    else
        tac="tail -r"
    fi

    BUFFER=$(\history -n 1 | eval $tac | peco --query "$LBUFFER")
    CURSOR=$#BUFFER
    zle clear-screen
}

zle -N search_history

bindkey -e
bindkey '^r' search_history

# rbenv
eval "$(rbenv init -)"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.homebrew_github_api_token)
export EDITOR=vi
export VISUAL=vi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# powerline conf
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir_joined vcs)

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
